apiVersion: v1
kind: ConfigMap
metadata:
  name: onboarding-config
  namespace: onboarding-exercise
data:
  POSTGRES_DB: onboarding_exercise_db
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
---
apiVersion: v1
kind: Secret
metadata:
  name: onboarding-secrets
  namespace: onboarding-exercise
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
