apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: onboarding-exercise
type: Opaque
data:
  # Base64 encoded values for your database
  # echo -n "admin" | base64 = YWRtaW4=
  # echo -n "password" | base64 = cGFzc3dvcmQ=
  # echo -n "onboarding_exercise_db" | base64 = b25ib2FyZGluZ19leGVyY2lzZV9kYg==
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: b25ib2FyZGluZ19leGVyY2lzZV9kYg==
